myDict={"one":1,2:"two",3:[90,5,5,6],"one":True,"apple":33,"one":11,(22,33,44):4}
print("the items of mydictionary is:",myDict)
print("the type of myDict is:", type(myDict))
print("list of items",myDict.items())
print("only keys", myDict.keys())
print("only values",myDict.values())
myDict.pop(2)
print("after removing values::",myDict)
print("size of mydictionary:", len(myDict))
# myDict.clear()
# print("after clearing all elements:", myDict)

print("accessing particular elements:",myDict.__getitem__("apple"))
myDict.__delitem__("apple")
print("reversed of items",myDict)
mycopy=myDict.copy()
print("copy of elements:",mycopy)
myDict.update({'one':"first"})
print("after updating values are", myDict)
